### ISSUE TITLE
Pull up voltages

### ISSUE THREAD

**Issue by benhadad** [Upcycle-Electronics/CH341A-Pro#1]
Is it possible to show the pull up voltages on the tracing?  I have heard that the MISO an other lines are still 5V on some models where they should be 3.3v.  Is there a way to confirm with your schematic what they are?

I have seen ways to convert this to real 3.3v, can we get 3 diagrams 1.(as is) 2.modified for 3.3v only 3. modified for 5v only.

**Comment by Upcycle-Electronics** [comment]
This is just a retrace showing exactly what I found on my board after removing all components, and a transparent overlay showing both sides.

  Don't rely on the following, but if I recall correctly from over 3 months ago... The chip itself has the internal weak pull up resistors. Read the datasheet to confirm this.

   The chip is supplied at 5 volts. If you want a proper 3v3 setup the chip should be powered from 3v3. If you study the included images here, you should clearly see that the 3v3 rail passes right beside the trace going to VCC on the chip. Use the pictures to figure out where you have access and want to cut the trace that powers the chip and add a bodge wire to connect this trace to the 3v3 rail. 
  If I were doing this, and wanted to use this programmer, I would get 2 of these programmers and mark/use one of them for 3v3 only and the other for 5v0. For the 3v3 version, I would cut the 5 volt power trace so that only the 3v3 regulator is connected to 5V. This way there is no potential for screw-ups. 

Use this:
https://github.com/Upcycle-Electronics/CH341A-Pro/blob/master/ch341aProMain.jpeg
and this:
https://raw.githubusercontent.com/Upcycle-Electronics/CH341A-Pro/master/ch341aProA%2B.jpeg
to line everything up. If you look, up at the top left of the first image, between the 5 volt and 3v3 power pins of the regulator, there is a place where both power traces cross each other at almost 90 degrees. It is just to the right of where the 5 volt trace goes through the via to the back of the board. 
1.) Find this trace on the back of your board and cut it near the via on the USB side of the trace. 
2.) Then match up the place where the first image shows the traces cross, use the second image to match up the location with things you can identify on your board. 
3.) Remove the solder mask from this area on the traces on both sides of the board (much easier to do this before drilling than after)
4.) Then use a 0.6-1.0mm drill bit (I keep a bunch of 0.8mm in my toolbox) to make a hole through the board and both traces. If you haven't done this before, it's best to use high speed, very light pressure, and have the back side of the board pressed against some kind of scap backing material like a piece of wood. It's easy to lift the back side trace if you're not careful. It's no big deal if you do lift the trace. Just replace it with a wire.
5.) Finally, solder a wire through the hole like a via and you're done. 
Easy peasy :-)
